(function() {
'use strict';
    angular
        .module("main.outage.outagestep1")
        .value("statesList", [
			{abrev: "AL", name: "Alabama"},
			{abrev: "AK", name: "Alaska"},
			{abrev: "AZ", name: "Arizona"},
			{abrev: "AR", name: "Arkansas"},
			{abrev: "CA", name: "California"},
			{abrev: "CO", name: "Colorado"},
			{abrev: "CT", name: "Connecticut"},
			{abrev: "DE", name: "Delaware"},
			{abrev: "DC", name: "District of Columbia"},
			{abrev: "FL", name: "Florida"},
			{abrev: "GA", name: "Georgia"},
			{abrev: "HI", name: "Hawaii"},
			{abrev: "ID", name: "Idaho"},
			{abrev: "IL", name: "Illinois"},
			{abrev: "IN", name: "Indiana"},
			{abrev: "IA", name: "Iowa"},
			{abrev: "KS", name: "Kansas"},
			{abrev: "KY", name: "Kentucky"},
			{abrev: "LA", name: "Louisiana"},
			{abrev: "ME", name: "Maine"},
			{abrev: "MD", name: "Maryland"},
			{abrev: "MA", name: "Massachusetts"},
			{abrev: "MI", name: "Michigan"},
			{abrev: "MN", name: "Minnesota"},
			{abrev: "MS", name: "Mississippi"},
			{abrev: "MO", name: "Missouri"},
			{abrev: "MT", name: "Montana"},
			{abrev: "NE", name: "Nebraska"},
			{abrev: "NV", name: "Nevada"},
			{abrev: "NH", name: "New Hampshire"},
			{abrev: "NJ", name: "New Jersey"},
			{abrev: "NM", name: "New Mexico"},
			{abrev: "NY", name: "New York"},
			{abrev: "NC", name: "North Carolina"},
			{abrev: "ND", name: "North Dakota"},
			{abrev: "OH", name: "Ohio"},
			{abrev: "OK", name: "Oklahoma"},
			{abrev: "OR", name: "Oregon"},
			{abrev: "PA", name: "Pennsylvania"},
			{abrev: "RI", name: "Rhode Island"},
			{abrev: "SC", name: "South Carolina"},
			{abrev: "SD", name: "South Dakota"},
			{abrev: "TN", name: "Tennessee"},
			{abrev: "TX", name: "Texas"},
			{abrev: "UT", name: "Utah"},
			{abrev: "VT", name: "Vermont"},
			{abrev: "VA", name: "Virginia"},
			{abrev: "WA", name: "Washington"},
			{abrev: "WV", name: "West Virginia"},
			{abrev: "WI", name: "Wisconsin"},
			{abrev: "WY", name: "Wyoming"}
		]);

})();

